version: "3"

services:
  mongo:
    container_name: mongo
    build:
      context: mongo
      dockerfile: Dockerfile
    ports:
      - 27017:27017

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.local
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/evently?readPreference=primary&directConnection=true&ssl=false
      - HTTP_CORS_CREDENTIALS=true
    volumes:
      - ./backend/src:/app/src
    expose:
      - 4000
    ports:
      - 4000:4000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.evently.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
    depends_on:
      - mongo

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NEXT_PUBLIC_BASE_API_URL=http://api.evently.localhost
    expose:
      - 3000
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`evently.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"

  traefik:
    image: "traefik:v2.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
