FROM node:16-alpine3.11

RUN apk add g++ make python

RUN apk --no-cache add --virtual \
  builds-deps \
  build-base \
  python

RUN apk add --update alpine-sdk && \
    apk add libffi-dev openssl-dev && \
    apk add python-dev python3-dev

WORKDIR /app

ADD package.json package-lock.json tsconfig.json nodemon.json ./

RUN npm install

RUN npm rebuild bcrypt --build-from-source

CMD ["npm", "run", "dev"]
